config/routes.rb
Rails.application.routes.draw do
  get '/users/topnews' => 'users#topnews'
  get '/users/wired' => 'users#wired'
  resources :users

end

app/models/magazine.rb
# require 'config/initializers/twitter.rb'
require 'twitter'
class Magazine < ActiveRecord::Base

  def self.wired

     client = Twitter::REST::Client.new do |config|
     config.consumer_key         = ENV['CONSUMER_KEY']
     config.consumer_secret      = ENV['CONSUMER_SECRET']
     config.access_token         = ENV['YOUR_ACCESS_TOKEN']
     config.access_token_secret  = ENV['YOUR_ACCESS_SECRET']
   end

  client.get("https://api.twitter.com/1.1/search/tweets.json?q=from%3Awired&src=typd")
  end

  def self.topnews
     client = Twitter::REST::Client.new do |config|
     config.consumer_key         = ENV['CONSUMER_KEY']
     config.consumer_secret      = ENV['CONSUMER_SECRET']
     config.access_token         = ENV['YOUR_ACCESS_TOKEN']
     config.access_token_secret  = ENV['YOUR_ACCESS_SECRET']
  end
   client.get("https://api.twitter.com/1.1/search/tweets.json?q=%23news%20lang%3Aen")
 end




end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def wired
  search_results = Magazine.wired[:statuses];
  p search_results
  render json: search_results
  end

  def topnews
  search_results = Magazine.topnews[:statuses];
  p search_results
  render json: search_results
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    render :partial => 'form'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest, :nytimes, :wired, :weather, :soccer, :topnews)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">

  <head>



  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

   <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>




  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>


</head>

<body style="background-color:#727A69;font-family: 'Raleway', sans-serif;color:white;margin:0">

  <div class="cover"></div>
  <div class="container-fluid" id="first">


    <h1 style="margin-left:2%;">The Daily News
      <br><span>
   <div class="signup"><%= link_to 'Sign Up!', new_user_path%></div></span></h1>


  <form role="form" style="margin-left:55%;">
  <div class="form-group">
    <p style="color:white;font-family: 'Raleway', sans-serif;">Login:</p>
    <input type="name" class="form-control" id="username" placeholder="username">
  </div>
   <div class="form-group">

    <input type="name" class="form-control" id="password" placeholder="password">
  </div>
</form>
</div>
<br>
<div class="jumbotron" id="tag">
  <!-- <h1 style="color:red;font-size:55px;">DAILY NEWS</h1> -->
<img src="http://fontmeme.com/embed.php?text=The%20Daily%20News&name=Chenier-Regular.ttf&size=90&style_color=17171C" alt="Typewriter Fonts">


</div>
  <div class="container-fluid" id="topdash">

  <div class="row" class="main">
    <div class="col-md-4" class="nytimesbutton"/>
   <img src="http://fontmeme.com/embed.php?text=New%20York%20Times&name=
BLACEB__.ttf&size=40&style_color=FFFFFF" alt="Old English Fonts">
     </div>
    <div class="col-md-4" class="wiredbutton"/>
<img src="http://fontmeme.com/embed.php?text=Wired&name=persans.ttf&size=40&style_color=F7F7F7" alt="Sans Serif Fonts" style="margin-top:5px">
    </div>
     <div class="col-md-4" class="topnewsbutton"/>
      <img src="http://fontmeme.com/embed.php?text=Top%20News&name=Cardo104s.ttf&size=40&style_color=FFFFFF" alt="Serif Fonts">
    </div>
</div>


    <div class="row" class="main">
    <div class="col-md-4" class="sportsbutton"/>
      <img style="margin-top:10px;" src="http://fontmeme.com/embed.php?text=Soccer&name=PICOBLA_.ttf&size=40&style_color=FFFFFF" alt="Web 2.0 Fonts">

    </div>
    <div class="col-md-4" class="button"/>
 <img src="http://fontmeme.com/embed.php?text=Coming%20Shortly&name=
Pacifico.ttf&size=40&style_color=FFFFFF" alt="Script Fonts">
     </div>
    <div class="col-md-4" class="weatherbutton" />
  <img src="http://fontmeme.com/embed.php?text=The%20Weather%20Channel&name=OpenSans-Bold.ttf&size=40&style_color=FFFFFF" alt="Sans Serif Fonts">
    </div>
</div>





  <%=yield%>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>


</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
      <% end %>
 <div class="form-holder">
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :nytimes %><br>
    <%= f.check_box :nytimes %>
  </div>
  <div class="field">
    <%= f.label :wired %><br>
    <%= f.check_box :wired%>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.check_box :weather %>
  </div>
  <div class="field">
    <%= f.label :soccer %><br>
    <%= f.check_box :soccer %>
  </div>
  <div class="field">
    <%= f.label :topnews %><br>
    <%= f.check_box :topnews %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>
</div>

app/views/users/_npr.html.erb
`<div ng-controller="NprCtrl" class="npr-div" class="col-md-6">
      <h4 style="margin-left:30px;font-weight:bold;">NPR</h4>
    <ul ng-repeat="item in items"><li></li>
      <li>{{item.type}}</li>
      <li>{{item.title}}</li>
      <li>{{item.additionalInfo}}</li>

    </ul>
  </div>

app/views/users/_nytimes.html.erb
<div ng-controller="NyCtrl" class="nydata-div" class="col-md-6">
      <h4 style="margin-left:30px;font-weight:bold;">Articles from The New York Times</h4>
    <ul ng-repeat="section in sections" class="nydata">
      <a href="{{section.url}}"><li>{{section.title}}</li></a>
      <li>--{{section.abstract}}</li>
      <li>Published on {{section.published_date}}</li>
    </ul>
  </div>

app/views/users/_soccer.html.erb
<div ng-controller="SportsCtrl" class="sports-div" class="col-md-6">
<h4>Premier League</h4>
<ul ng-repeat="stat in stats">
<li>Position:{{stat.position}} Team: {{stat.teamName}} Points: {{stat.points}}
</li>
</ul>


</div>

app/views/users/_twitter.html.erb
<div ng-controller="TwitterCtrl"class="twitter-div" class="col-md-6">
<h4> Wired News</h4>
<ul ng-repeat="article in articles">
<li>{{article.text}}</li>

</ul>
</div>

app/views/users/_vice.html.erb
<div ng-controller="ViceCtrl"class="topnews-div" class="col-md-6">
<h4>Top News</h4>
<ul ng-repeat="article in articles">
<p>{{article.text}}</p>
</ul>
</div>

app/views/users/_weather.html.erb
<div ng-controller="WeatherCtrl" class="weather-div" class="col-md-6">


      <h5 >Current Temperature: {{stuffs.temp}}</h5>
      <p >Today's High: {{stuffs.temp_max}}</p>
      <p >Today's Low: {{stuffs.temp_min}}</p>

  </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%= render 'form' %>

<h1 class="new">Sign Up!</h1>
<div class="back"><%= link_to 'Back', users_path %></div>

app/views/users/show.html.erb
<div class="special" class="row" style="box-shadow:none;background-color:none;">

<img class="down-arrow" class="img-responsive" src="http://www.clker.com/cliparts/C/C/t/u/L/0/arrow-down-gray-hi.png"/>

<img class="up-arrow" class="img-responsive" src="http://www.successacademies.org/site/themes/success-academy/assets/img/arrow--up--gray.png"/>
</div>
<!-- </div> -->

<div class="container-fluid" id="second">
<h2>My News Feed</h2>

<% if @user.nytimes == true %>
<%= render :partial => 'nytimes'%>
<% end %>

<% if @user.weather == true %>
<%= render :partial => 'weather'%>
<% end %>

<% if @user.soccer == true %>
<%= render :partial => 'soccer'%>
<% end %>

<% if @user.topnews == true %>
<%= render :partial => 'vice'%>
<% end %>

<% if @user.wired == true %>
<%= render :partial => 'twitter'%>
<% end %>

</div>